name: foodie
description: Foodie is food delivery mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.6.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.1
  basic_utils: ^3.3.3
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.3.1
  country_picker: ^1.1.3
  dartx: ^0.7.1
  dio_cache_interceptor: ^3.0.1
  edge_alert: ^0.0.1
  file_picker: ^3.0.3
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_messaging: ^10.0.3
  flag: ^3.2.2
  floor: ^1.1.0
  flutter_custom_clippers: ^1.1.1
  flutter_icons: ^1.0.0+1
  flutter_local_notifications: ^1.4.4+2
  flutter_staggered_animations: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  flutter_xlider: ^3.4.0
  flutterlifecyclehooks: ^1.0.0
  form_validator: ^0.1.7
  google_fonts: ^2.1.0
  google_map_location_picker: ^4.1.7
  google_sign_in: ^4.5.1
  i18n_extension: ^4.0.0
  intl: ^0.16.0
  location: ^4.3.0
  location_permissions: ^4.0.0
  lottie: ^1.1.0
  material_segmented_control: ^2.1.0+1
  otp_text_field: ^1.0.2
  pull_to_refresh: ^1.6.4
  random_color: ^1.0.5
  random_string: ^2.1.0
  rating_bar: ^0.2.0
  razorpay_flutter: ^1.1.4
  readmore: ^2.0.0
  rxdart: ^0.24.1
  shared_preferences: ^2.0.6
  shimmer: ^1.1.1
  smooth_page_indicator: ^0.1.5
  stacked: ^1.7.6
  timer_count_down: ^1.0.4+1
  url_launcher: ^5.5.0
  velocity_x: ^2.6.0

dependency_overrides:
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  args: ^2.0.0
  flutter_application_id: ^1.0.0
  webview_flutter: ^2.0.9
  flutterwave: ^0.0.3-dev.2
  http: ^0.13.3
  dio: ^4.0.0
  paystack_manager: ^1.0.3
  plugin_platform_interface: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  floor_generator: ^1.1.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/lottie/
